on:
  pull_request:
    types: [synchronize]    
    branches:
    - main
    
jobs:
  update_taktile_nodes:    
    runs-on: ubuntu-22.04
    steps:
      - name: Prepare data body to post to API
        run: |
          echo '{
            "data": {
            },
            "metadata": {
              "version": "v1.0",
              "entity_id": "string"
            },
            "control": {
              "execution_mode": "sync"
            }
          }' > data_body.json
      
      - name: Get Organization flow_id
        run: | 
          # Prepare data to post to get flow_id from organization
          jq --arg org_name "${{ vars.ORG_NAME }}" '.data |= (.organization_name = $org_name)' data_body.json > list_flows_data.json

          # Post to List Decision Flows API to obtain List of Flows
          curl -s https://eu-central-1.taktile-org.decide.taktile.com/run/api/v1/flows/list-decision-graphs/sandbox/decide -H 'accept: application/json' -H 'Content-Type: application/json' -H "X-API-Key: ${{ secrets.TAKTILE_API_KEY }}" -d @list_flows_data.json > flow_res.json 

          # # Parse flow_id from response 
          # #! Here I am assuming that this org only has one flow
          # #! Another algorithm that iterates over flows to update specific python files might be necessary
          flow_id=$(jq -r '.data.flows[].flow_id' flow_res.json)
      - name: Get and Parse decision graph information
        run: |
          # Get Decision graph for a flow_id
          jq --arg flow_id "$flow_id" '.data |= (.flow_id = $flow_id)' data_body.json > get_dec_graph_data.json

          curl -s https://eu-central-1.taktile-org.decide.taktile.com/run/api/v1/flows/get-decision-graph/sandbox/decide -H 'accept: application/json' -H 'Content-Type: application/json' -H "X-API-Key: ${API_KEY}" -d @get_dec_graph_data.json > dec_graph_res.json
          echo "::debug::$(jq '.' dec_graph_res.json)"
      - name: Parse data on code nodes to update
        run: |
          # Parse node information from decision graph to prepare code update
          FILES_TO_UPDATE=("Multiply" "Summarize")

          for file_name in $FILES_TO_UPDATE 
          do
            jq --arg file "$file_name" '.data.graph[]  | select(.node_name == $file) | {name: .node_name, node_id: .node_id, src_code: .meta.src_code}' dec_graph_res.json >> to_update.json
          done 
          
          echo $(cat to_update.json)
          
